remote_theme: jurakovic/cayman-blue
google_analytics: G-233EMZJM16
dark_theme: true
target_blank: [header, main]
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "blogs/index.html"
      type: "pages"
    values:
      title: "dev-blogs"
